name: CI/CD - SAST + DAST + SCA

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  actions: write

jobs:
  # ------------------------------
  # SAST - Semgrep
  # ------------------------------
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep (logs)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/default
        continue-on-error: true

      - name: Generate Semgrep JSON report
        run: |
          python -m pip install --upgrade pip semgrep
          semgrep --config p/default --json > semgrep-report.json || true

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json
          retention-days: 7

  # ------------------------------
  # DAST - OWASP ZAP
  # ------------------------------
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://testphp.vulnweb.com"
          cmd_options: "-a -r zap-report.html"
          artifact_name: "zap-report"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
          retention-days: 7

  # ------------------------------
  # SCA - pip-audit + Dependency Review
  # ------------------------------
  sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pip-audit
        run: python -m pip install --upgrade pip pip-audit

      - name: Run pip-audit (JSON)
        run: pip-audit -r requirements.txt -f json > sca-report.json || true

      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        with:
          name: sca-report
          path: sca-report.json
          retention-days: 7
