name: DAST - OWASP ZAP

on:
  workflow_dispatch:   # permite rodar manualmente
  push:
    branches: [ "main" ]

permissions:
  contents: read   # permissões mínimas para as actions

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: "http://testphp.vulnweb.com"   # site de teste vulnerável
          cmd_options: "-a -r report.html"       # gera HTML do relatório

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report.html
          retention-days: 7
          

