name: DAST - OWASP ZAP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://testphp.vulnweb.com"   # alvo de teste
          cmd_options: "-a -r zap-report.html"   # gera o relatório HTML
          artifact_name: "zap-report"            # faz upload automático como artifact

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
          retention-days: 7
