name: SAST - Semgrep

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c¢digo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Semgrep
        run: pip install semgrep

      - name: Rodar an lise SAST
        run: semgrep --config auto src/ --error
