name: SCA - Dependency Review & pip-audit

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  # Mostra riscos em PR (não gera arquivo)
  dependency_review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency Review (PR diff)
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high

  # Gera relatório baixável com pip-audit
  pip_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug – listar arquivos
        run: ls -lah

      - name: Garantir requirements.txt existe
        shell: bash
        run: |
          if [ ! -s "requirements.txt" ]; then
            echo 'Nenhum requirements.txt encontrado ou arquivo vazio.' > sca-report.txt
            echo '{"info":"Nenhum requirements.txt encontrado ou arquivo vazio.","results":[]}' > sca-report.json
            exit 0
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pip-audit
        run: python -m pip install --upgrade pip pip-audit

      # Use -o para escrever o arquivo mesmo se o retorno for não-zero
      - name: Run pip-audit (gera JSON)
        run: |
          pip-audit -r requirements.txt -f json -o sca-report.json || true
          # Também um TXT legível, opcional:
          pip-audit -r requirements.txt > sca-report.txt || true

      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        with:
          name: sca-report
          path: |
            sca-report.json
            sca-report.txt
          retention-days: 7
